#!/bin/bash
read -p "Input command: " command
read -p "Input destination file: " dest
read -p "Input base value: " n
read -p "Input delta: " delta

touch $dest
cat /dev/null > $dest

for i in {0..10}
do
    let "x =$n + $delta * $i"
    echo -e `$command $x` >> $dest
done
