#!/bin/bash

dest="delta_ms"
touch $dest
cat /dev/null > $dest
delta=3550
n=1500
for i in {0..10}
do
    let "x =$n + $delta * $i"
    echo -e `./main $x` >> $dest
    sudo bash -c "sync; echo 1 > /proc/sys/vm/drop_caches"
done
